# -*- coding: utf-8 -*-
"""zomato

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZIM7sSNvcunXuzDPni4vREN6IuVmBxTv
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
df = pd.read_csv('/content/zomato.csv')

df.info()

df.head()

df.tail()

df['rate'] = df['rate'].astype(str).str.replace('/5', '', regex=False)
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')
df.info()

df['cost'] = pd.to_numeric(df['approx_cost(for two people)'], errors='coerce')
df.info()

df.dropna(subset=['rate','cost','cuisines'], inplace=True)
df.info()

plt.figure(figsize=(8, 5))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

text = " ".join(df['cuisines'].dropna())
wc = WordCloud(width=800, height=400, background_color='white').generate(text)
plt.figure(figsize=(10, 6))
plt.imshow(wc)
plt.axis('off')
plt.title('Word Cloud of Cuisines')
plt.show()

plt.figure(figsize=(10, 6))
df.groupby('location')['rate'].mean().sort_values(ascending=False).plot(kind='bar', color='teal')
plt.title('Average Rating by Location')
plt.xlabel('Location')
plt.ylabel('Average Rating')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='cost', y='rate', data=df, alpha=0.5)
plt.title('Restaurant Rating vs. Approximate Cost for Two People')
plt.xlabel('Approximate Cost (for two people)')
plt.ylabel('Rating')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

